### ISSUE TITLE
`nattka apply --keywordreq -a ia64 -n` fails as: ValueError: '/gentoo-ebuilds/gentoo' repo already configured

### ISSUE THREAD

**Issue by trofi** [mgorny/nattka#25]
I'm not sure what the tool tries to configure. The error message could probably be improved to state the actual problem.

```
gentoo.git $ nattka apply --keywordreq -a ia64 -n

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/nattka", line 11, in <module>
    load_entry_point('nattka==0.1.2', 'console_scripts', 'nattka')()
  File "/usr/lib64/python3.6/site-packages/nattka/cli.py", line 711, in setuptools_main
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib64/python3.6/site-packages/nattka/cli.py", line 702, in main
    return getattr(cmd, args.command.replace('-', '_'))()
  File "/usr/lib64/python3.6/site-packages/nattka/cli.py", line 210, in apply
    repo = self.get_repository()
  File "/usr/lib64/python3.6/site-packages/nattka/cli.py", line 140, in get_repository
    is not None else None)
  File "/usr/lib64/python3.6/site-packages/nattka/package.py", line 89, in find_repository
    configure=False))
  File "/usr/lib64/python3.6/site-packages/pkgcore/ebuild/domain.py", line 659, in find_repo
    repo = self.add_repo(path, config=config, configure=configure)
  File "/usr/lib64/python3.6/site-packages/pkgcore/ebuild/domain.py", line 638, in add_repo
    raise ValueError(f'{name!r} repo already configured')
ValueError: '/gentoo-ebuilds/gentoo' repo already configured
```

**Comment by mgorny** [comment]
Which version did you try? I've fixed one bug like this in the past.

**Comment by trofi** [comment]
```
=================================================================
                        Package Settings
=================================================================

app-portage/nattka-0.1.2::gentoo was built with the following:
USE="-doc -test" ABI_X86="(64)" PYTHON_TARGETS="python3_6 -python3_7 -python3_8"
FEATURES="news multilib-strict userpriv fail-clean binpkg-docompress pid-sandbox ccache unmerge-logs sfperms protect-owned clean-logs ebuild-locks network-sandbox distlocks fixlafiles assume-digests sign sandbox xattr binpkg-logs merge-sync qa-unresolved-soname-deps parallel-fetch config-protect-if-modified unknown-features-warn ipc-sandbox binpkg-dostrip userfetch usersync usersandbox strict unmerge-orphans preserve-libs"
```

**Comment by mgorny** [comment]
Are there any symlinks involved? Does `pkgcheck scan` work inside that repo?

**Comment by trofi** [comment]
I'm not sure they are involved.

```
$ emerge --info | fgrep location
    location: /gentoo-ebuilds/gentoo
    location: /home/slyfox/portage/cross
    location: /gentoo-ebuilds/gentoo-haskell
    location: /home/slyfox/portage/nix-guix-gentoo
    location: /home/slyfox/portage/slyfox-gentoo
$ ls -ld /gentoo-ebuilds/gentoo /home/slyfox/portage/cross /gentoo-ebuilds/gentoo-haskell /home/slyfox/portage/nix-guix-gentoo /home/slyfox/portage/slyfox-gentoo
drwxr-xr-x 177 slyfox users 6144 апр  9 23:01 /gentoo-ebuilds/gentoo
drwxr-xr-x  46 slyfox users 1024 мар 22 08:59 /gentoo-ebuilds/gentoo-haskell
drwxr-xr-x  46 slyfox users 3072 дек 22 22:36 /home/slyfox/portage/cross
drwxr-xr-x   6 slyfox users 1024 ноя 25 21:06 /home/slyfox/portage/nix-guix-gentoo
drwxr-xr-x  15 slyfox users 1024 фев 11 23:27 /home/slyfox/portage/slyfox-gentoo
```

```
$ cd /gentoo-ebuilds/gentoo
$ pkgcheck scan .
...
updating gentoo git repo cache: 119f9d6ab000d -> c847c68c83dec
acct-group/abrt
  UnstableOnly: for arch: [ riscv ], all versions are unstable: [ 0 ]
  PotentialStable: version 0: slot(0), stabled arches: [ alpha, amd64, arm, arm64, hppa, ia64, m68k, ppc, ppc64, s390, sparc, x86 ], potential: [ ~riscv ]
...
$ pkgcheck scan
acct-group/audio
  UnstableOnly: for arch: [ riscv ], all versions are unstable: [ 0 ]
  PotentialStable: version 0: slot(0), stabled arches: [ alpha, amd64, arm, arm64, hppa, ia64, m68k, ppc, ppc64, s390, sparc, x86 ], potential: [ ~riscv ]
...
$ nattka apply --keywordreq -a ia64 -n
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/nattka", line 11, in <module>
    load_entry_point('nattka==0.1.2', 'console_scripts', 'nattka')()
  File "/usr/lib64/python3.6/site-packages/nattka/cli.py", line 711, in setuptools_main
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib64/python3.6/site-packages/nattka/cli.py", line 702, in main
    return getattr(cmd, args.command.replace('-', '_'))()
  File "/usr/lib64/python3.6/site-packages/nattka/cli.py", line 210, in apply
    repo = self.get_repository()
  File "/usr/lib64/python3.6/site-packages/nattka/cli.py", line 140, in get_repository
    is not None else None)
  File "/usr/lib64/python3.6/site-packages/nattka/package.py", line 89, in find_repository
    configure=False))
  File "/usr/lib64/python3.6/site-packages/pkgcore/ebuild/domain.py", line 659, in find_repo
    repo = self.add_repo(path, config=config, configure=configure)
  File "/usr/lib64/python3.6/site-packages/pkgcore/ebuild/domain.py", line 638, in add_repo
    raise ValueError(f'{name!r} repo already configured')
ValueError: '/gentoo-ebuilds/gentoo' repo already configured
```

**Comment by mgorny** [comment]
Hmm, I think I see the problem. Could you try whether passing `--repo <full-path>` works?

**Comment by trofi** [comment]
```
$ cd /gentoo-ebuilds/gentoo
$ nattka --repo $PWD apply --keywordreq -a ia64 -n
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/nattka", line 11, in <module>
    load_entry_point('nattka==0.1.2', 'console_scripts', 'nattka')()
  File "/usr/lib64/python3.6/site-packages/nattka/cli.py", line 711, in setuptools_main
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib64/python3.6/site-packages/nattka/cli.py", line 702, in main
    return getattr(cmd, args.command.replace('-', '_'))()
  File "/usr/lib64/python3.6/site-packages/nattka/cli.py", line 210, in apply
    repo = self.get_repository()
  File "/usr/lib64/python3.6/site-packages/nattka/cli.py", line 140, in get_repository
    is not None else None)
  File "/usr/lib64/python3.6/site-packages/nattka/package.py", line 89, in find_repository
    configure=False))
  File "/usr/lib64/python3.6/site-packages/pkgcore/ebuild/domain.py", line 659, in find_repo
    repo = self.add_repo(path, config=config, configure=configure)
  File "/usr/lib64/python3.6/site-packages/pkgcore/ebuild/domain.py", line 638, in add_repo
    raise ValueError(f'{name!r} repo already configured')
ValueError: '/gentoo-ebuilds/gentoo' repo already configured
```
```
$ cd /
$ nattka --repo /gentoo-ebuilds/gentoo apply --keywordreq -a ia64 -n
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/nattka", line 11, in <module>
    load_entry_point('nattka==0.1.2', 'console_scripts', 'nattka')()
  File "/usr/lib64/python3.6/site-packages/nattka/cli.py", line 711, in setuptools_main
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib64/python3.6/site-packages/nattka/cli.py", line 702, in main
    return getattr(cmd, args.command.replace('-', '_'))()
  File "/usr/lib64/python3.6/site-packages/nattka/cli.py", line 210, in apply
    repo = self.get_repository()
  File "/usr/lib64/python3.6/site-packages/nattka/cli.py", line 140, in get_repository
    is not None else None)
  File "/usr/lib64/python3.6/site-packages/nattka/package.py", line 89, in find_repository
    configure=False))
  File "/usr/lib64/python3.6/site-packages/pkgcore/ebuild/domain.py", line 659, in find_repo
    repo = self.add_repo(path, config=config, configure=configure)
  File "/usr/lib64/python3.6/site-packages/pkgcore/ebuild/domain.py", line 638, in add_repo
    raise ValueError(f'{name!r} repo already configured')
ValueError: '/gentoo-ebuilds/gentoo' repo already configured
```

**Comment by mgorny** [comment]
Could you try -9999? I've just pushed some changes to the repository finding logic, maybe they'll fix your case as well.

**Comment by trofi** [comment]
Seems to work.

```
# emerge -v1 app-portage/nattka
   repository:               https://github.com/mgorny/nattka.git
   at the commit:            cb66f80af76159b4830985ba5287b58844141b5c
...
>>> Merging app-portage/nattka-9999 to /
```

```
$ cd /gentoo-ebuilds/gentoo
$ nattka --repo $PWD apply --keywordreq -a ia64 -n
WARNING:nattka:Unable to import nattka.depgraph, dependency sorting will not be available
WARNING:nattka:(nattka.depgraph requires networkx)
WARNING:nattka:No API key provided, will run unauthorized queries
WARNING:nattka:(pass --api-key or put it in ~/.bugz_token)
# bug 711488 (KEYWORDREQ)
=net-fs/samba-4.12.0 **  # -> ~ia64
=net-fs/samba-4.12.1 **  # -> ~ia64
=sys-libs/liburing-0.5 **  # -> ~ia64
...
```

```
$ cd /
$ nattka --repo /gentoo-ebuilds/gentoo apply --keywordreq -a ia64 -n
WARNING:nattka:Unable to import nattka.depgraph, dependency sorting will not be available
WARNING:nattka:(nattka.depgraph requires networkx)
WARNING:nattka:No API key provided, will run unauthorized queries
WARNING:nattka:(pass --api-key or put it in ~/.bugz_token)
# bug 711488 (KEYWORDREQ)
=net-fs/samba-4.12.0 **  # -> ~ia64
=net-fs/samba-4.12.1 **  # -> ~ia64
=sys-libs/liburing-0.5 **  # -> ~ia64
...
```

**Comment by mgorny** [comment]
Cool, thanks. I'm working on one more issue (#26) right now, then I'll look into #28 and then make a release.
