### ISSUE TITLE
Backtraces don't report bug that caused parse errors

### ISSUE THREAD

**Issue by trofi** [mgorny/nattka#28]
Invalid bug should be reported by number so one can go and fix them.

Example failures:

```
$ nattka --repo /gentoo-ebuilds/gentoo apply --keywordreq --arch hppa --ignore-sanity-check --ignore-dependencies -n

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/nattka", line 11, in <module>
    load_entry_point('nattka==0.1.2', 'console_scripts', 'nattka')()
  File "/usr/lib64/python3.6/site-packages/nattka/cli.py", line 717, in setuptools_main
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib64/python3.6/site-packages/nattka/cli.py", line 708, in main
    return getattr(cmd, args.command.replace('-', '_'))()
  File "/usr/lib64/python3.6/site-packages/nattka/cli.py", line 228, in apply
    plist = dict(match_package_list(repo, b, only_new=True))
  File "/usr/lib64/python3.6/site-packages/nattka/package.py", line 159, in match_package_list
    f'no match for package: {sl[0]}')
nattka.package.PackageNoMatch: no match for package: dev-util/gtk-update-icon-cache-3.24.13
```

Invalid keywords:

```
$ nattka --repo /gentoo-ebuilds/gentoo apply --keywordreq --arch m68k --ignore-sanity-check --ignore-dependencies -n

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/nattka", line 11, in <module>
    load_entry_point('nattka==0.1.2', 'console_scripts', 'nattka')()
  File "/usr/lib64/python3.6/site-packages/nattka/cli.py", line 717, in setuptools_main
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib64/python3.6/site-packages/nattka/cli.py", line 708, in main
    return getattr(cmd, args.command.replace('-', '_'))()
  File "/usr/lib64/python3.6/site-packages/nattka/cli.py", line 228, in apply
    plist = dict(match_package_list(repo, b, only_new=True))
  File "/usr/lib64/python3.6/site-packages/nattka/package.py", line 200, in match_package_list
    f'incorrect keywords: {" ".join(unknown_keywords)}')
nattka.package.KeywordNoMatch: incorrect keywords: sh
```

**Comment by mgorny** [comment]
I need to add exception catching to commands other than `sanity-check`.

**Comment by mgorny** [comment]
Actually, could you test it on -9999 before I make a release? The issues should be printed as comments, and cause `1` exit code now.

**Comment by trofi** [comment]
Does not crash and reports errors inline:

```
$ nattka --repo /gentoo-ebuilds/gentoo apply -a hppa --stablereq -n
...
# bug 706524: no match for package: dev-util/gtk-update-icon-cache-3.24.13
```
